language: generic

sudo: required

services:
  - docker

before-install:
  - docker build -t orashwan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true orashwan/docker-react npm run test