language: generic

sudo: required

services:
  - docker

before-install:
  - docker build -t Omar6120/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Omar6120/docker-react npm run test